### ISSUE TITLE
Another render bug

### ISSUE THREAD

**Issue by SevenSpheres** [LukeCEL/spritestest#1]
So I just realized that this repository has been updated with a new sprite texture. This new texture is causing some issues. It's easiest to show screenshots:

Old texture:
![hltau](https://user-images.githubusercontent.com/56284207/71536551-d24eae80-28cd-11ea-9ba6-2714244a9e73.png)

New texture:
![hltaubug](https://user-images.githubusercontent.com/56284207/71536556-d975bc80-28cd-11ea-8a9d-677735b9fc99.png)

**Comment by LukeCEL** [comment]
@SevenSpheres I believe I've fixed this. The .ssc file said `"blob.png"`, not `"27px.png"`. I guess that overrided the definition in the cmod.

**Comment by SevenSpheres** [comment]
Yes, fixed!
